#!/bin/bash

declare -i SUM=`cat "$1" | cut -d ';' -f 11 | grep -oE '^[0-9]*' | awk '{s+=$1} END {print s}'`
declare -i COUNT=`cat "$1" | cut -d ';' -f 11 | grep -oE '^[0-9]*' | wc -l`
declare -i AVG=SUM/COUNT

echo "Average weight is $AVG"
